### ISSUE TITLE
Absolute paths of build server are baked into javascript files

### ISSUE THREAD

**Issue by fastner** [sebastian-software/edgestack#116]
When generating a prod version the absolute path of the build server is baked into the resulting javascript files, so manifest.json and assets.json could not be loaded

**Comment by swernerx** [comment]
Can you explain why this should be a problem? I mean you are typically building on the final machine... so the paths should be all available, right?

At least that's the case here in our production system.

Otherwise: What change do you expect?

**Comment by fastner** [comment]
No, in case of CI you never build on the final machine. build folder should be self contained in this case.

I would expect that both paths to manifest.json and assets.json are relative to server/main.js, so ../client/manifest.json in default env.example case.

**Comment by fastner** [comment]
Is there a specific reason for absolute local paths in this case?

**Comment by fastner** [comment]
To be more specific:

In **ConfigFactory.js** file there is a 

    ConfigFactory(target, mode, options = {}, root = CWD)

function that has a parameter root = CWD. This parameter is baked into packaging process of webpack to ````process.env.APP_ROOT````.

This one is only used in file **src/server/config.js**.

There are 4 constants in it that are used to load information data and static frontend files in server part.

When I see it right there is no reason to put the absolute path into the generated server file. The paths are not overwritable by configuration. They solve their purpose also when they are relative to the server directory.

**Comment by fastner** [comment]
Resolved
